[colors]
foreground = "#4c4f69"
background = "#eff1f5"
cursor = "#dc8a78"

ansi = [
  "#5c5f77", "#d20f39", "#40a02b", "#df8e1d",
  "#1e66f5", "#8839ef", "#179299", "#acb0be"
]

brights = [
  "#6c6f85", "#d20f39", "#40a02b", "#df8e1d",
  "#1e66f5", "#8839ef", "#179299", "#bcc0cc"
]
